language: generic

env:
- TYPE='hg' SRC='hg::https://hg.codeplex.com/koka'   DIR='koka'   DST="https://spl-deploy:$GITHUB_TOKEN@github.com/spl/koka.git"
- TYPE='hg' SRC='hg::https://hg.codeplex.com/madoko' DIR='madoko' DST="https://spl-deploy:$GITHUB_TOKEN@github.com/spl/madoko.git"

install:
- export PATH=$PWD:$PATH
- sh install-$TYPE.sh

script:
- sh script-$TYPE.sh
