language: generic

addons:
  apt:
    packages:
    - git-svn

env:
- TYPE='svn' SRC='http://svn.resourcespace.com/svn/rs/' DIR='resourcespace' DST="https://spl-deploy:$GITHUB_TOKEN@github.com/spl/resourcespace.git"

before_install:
# Error if $GITHUB_TOKEN is null.
- bash -c '[ -n "$GITHUB_TOKEN" ]'
# Error if $SRC is not accessible.
- curl -sSf $SRC > /dev/null

install:
- export PATH=$PWD:$PATH
- bash -x install-$TYPE.sh

script:
- bash -x script-$TYPE.sh
