language: generic

addons:
  apt:
    packages:
    - git-svn

env:
- TYPE='hg'  SRC='hg::https://hg.codeplex.com/koka'                    DIR='koka'   DST="https://spl-deploy:$GITHUB_TOKEN@github.com/spl/koka.git"
- TYPE='hg'  SRC='hg::https://hg.codeplex.com/madoko'                  DIR='madoko' DST="https://spl-deploy:$GITHUB_TOKEN@github.com/spl/madoko.git"
- TYPE='svn' SRC='https://svn.science.uu.nl/repos/sci.hage0101.helium' DIR='helium' DST="https://spl-deploy:$GITHUB_TOKEN@github.com/spl/helium.git"
- TYPE='svn' SRC='https://svn.science.uu.nl/repos/sci.hage0101.lvm'    DIR='lvm'    DST="https://spl-deploy:$GITHUB_TOKEN@github.com/spl/lvm.git"
- TYPE='svn' SRC='https://svn.science.uu.nl/repos/sci.hage0101.Top'    DIR='top'    DST="https://spl-deploy:$GITHUB_TOKEN@github.com/spl/top.git"
- TYPE='svn' SRC='https://svn.science.uu.nl/repos/sci.hage0101.hint'   DIR='hint'   DST="https://spl-deploy:$GITHUB_TOKEN@github.com/spl/hint.git"

before_install:
# Error if $GITHUB_TOKEN is null.
- bash -c '[ -n "$GITHUB_TOKEN" ]'

install:
- export PATH=$PWD:$PATH
- bash -x install-$TYPE.sh

script:
- bash -x script-$TYPE.sh
