language: generic

install:
  - wget https://raw.github.com/felipec/git-remote-hg/master/git-remote-hg -O ./git-remote-hg
  - chmod u+x ./git-remote-hg
  - export PATH=$PWD:$PATH

script:
  - git clone --mirror 'hg::https://hg.codeplex.com/koka'   koka
  - git clone --mirror 'hg::https://hg.codeplex.com/madoko' madoko
  - cd koka
  - ls -laF
  - git remote add mirror https://spl-deploy:$GITHUB_TOKEN@github.com/spl/koka.git
  - git push --mirror mirror
  - cd ../madoko
  - ls -laF
  - git remote add mirror https://spl-deploy:$GITHUB_TOKEN@github.com/spl/madoko.git
  - git push --mirror mirror
