install:
  - wget https://raw.github.com/felipec/git-remote-hg/master/git-remote-hg -O ./git-remote-hg
  - chmod u+x ./git-remote-hg

script:
  - PATH=.:$PATH git clone --mirror "hg::https://hg.codeplex.com/madoko" madoko
  - cd madoko/ &&
    git remote add mirror https://spl-deploy:$GITHUB_TOKEN@github.com/spl/madoko.git &&
    git push --mirror mirror
